name: "Bug support request 🐛"
description: "Create a request to fix a bug"
title: "[BUG] - <title>"
labels: ["type: bug 🐛"]

body:
  - type: markdown
    attributes:
      value: |
        Please fill out each section below. This info allows maintainers to diagnose (and fix!) your issue as
        quickly as possible.

  - type: textarea
    attributes:
      label: Describe the bug
      description: |
        A clear and concise description of what the bug is.
        We suggest using bullets (indicated by * or -).
      placeholder: Be as precise as you can.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: |
        A clear and concise description of what you expected to happen.
        We suggest using bullets (indicated by * or -).
    validations:
      required: true

  - type: textarea
    attributes:
      label: How to Reproduce the problem?
      description: |
        Please provide a minimal code example to reproduce the error.
        Be as concise as possible, and provide detailed step-by-step guidelines to reproduce the bug (using numbered items).
        If you created a GitHub gist, paste the link in this box instead.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Output
      description: |
        Provide the output of the steps above, including screenshots and any tracebacks/logs.

        Please also ensure that the "How to reproduce the problem?" section contains matching
        instructions for reproducing this.
    validations:
      required: false
      
  - type: dropdown
    attributes:
      label: Priority
      description: What is the priority level of this request?
      options:
        - High (I need this asap)
        - Medium (I need this soon, but nothing is on fire)
        - Low (I'd like this, but its not blocking anything)
      default: 2
    validations:
      required: true

  - type: textarea
    attributes:
      label: Versions and dependencies used.
      description: |
        Please include any relevant package versions.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Link to an open source issue? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
