name: "General request 💡"
description: "A general template for many kinds of issues and questions."
title: "<title>"
labels: ["needs: triaging 🚦"]

body:
  - type: markdown
    attributes:
      value: |
        Please fill out each section below. This info allows us to diagnose (and fix!) your issue or answer your question as
        quickly as possible.

  - type: textarea
    attributes:
      label: Context
      description: |
        Describe what you are experiencing. Provide as much context as possible and link to related issues and/or pull requests.

        Are you having any problems? Briefly describe what your pain points are.
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Priority
      description: What is the priority level of this request?
      options:
        - High (I need this asap)
        - Medium (I need this soon, but nothing is on fire)
        - Low (I'd like this, but its not blocking anything)
      default: 2
    validations:
      required: true

  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links to open source issues? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
